- name: install glusterfs client
  yum: name=glusterfs-client

- name: open firewall ports
  blockinfile:
    dest: /etc/sysconfig/iptables
    block: |
      -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24007 -j ACCEPT
      -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24008 -j ACCEPT
      -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2222 -j ACCEPT
      -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m multiport --dports 49152:49664 -j ACCEPT
    insertbefore: ^COMMIT
  register: iptables

- name: restart iptables service
  service: name=iptables state=restarted
  when: iptables|changed
