---
mem: 4096
vcpu: 2

disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2

  physvols:
    boot: 500
    rhel: 29500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048

repos:
  - rhel-7-server-rpms
  # - rhel-7-server-rhceph-2-mon-rpms
  # - rhel-7-server-rhceph-2-osd-rpms
  # - rhel-7-server-rhceph-2-tools-rpms
  # - rhel-7-server-rhscon-2-agent-rpms
  - rhel-7-server-rhscon-2-main-rpms
  - rhel-7-server-rhscon-2-installer-rpms

disable_services:
  - firewalld

pool_regex: "{{ ceph_subscription_pool_regex }}"
