- name: copy-import-manifest
  copy:  src=binary/{{ satellite_manifestfile }}
    dest=/root
    owner=root
    group=root
    mode=0600
  register: manifest

- name: upload manifest
  command: 'hammer subscription upload --organization "{{ organization }}" --file /root/{{ satellite_manifestfile }}'
  when: manifest|changed

- name: refresh manifest to warm up satellite (work around the fact that the first attempt times out)
  command: 'hammer subscription refresh-manifest --organization "{{ organization }}"'
  when: manifest|changed

- name: refresh manifest
  command: 'hammer subscription refresh-manifest --organization "{{ organization }}"'
#  when: not manifest|changed
