# --- Create necessary projects ticketmonster-dev and ticketmonster-prod for user developer:
- name: check existing projectsX
  shell: oc get projects | awk '{ print $1 }'
  register: projects
  changed_when: false

- name: Create ticketmonster-dev project
  shell: "oc adm new-project ticketmonster-dev --admin='developer' --description='ticket monster developers stage'"
  when: mode=="create" and 'ticketmonster-dev' not in projects.stdout_lines

- name: Reseting ticketmonster-dev project to empty state
  shell: oc delete all --all -n ticketmonster-dev
  when: "'ticketmonster-dev' in projects.stdout_lines"

- name: Create ticketmonster-prod project
  shell: "oc adm new-project ticketmonster-prod --admin='developer' --description='ticket monster production stage'"
  when: mode=="create" and 'ticketmonster-prod' not in projects.stdout_lines

- name: Reseting ticketmonster-prod project to empty state
  shell: oc delete all --all -n ticketmonster-prod
  when: "'ticketmonster-prod' in projects.stdout_lines"

# --- Create Templates monster and monster-prod in namespace openshift:
- name: check existing templates
  shell: oc get templates -n openshift | awk '{ print $1 }'
  register: templates
  changed_when: false

- block:
  - name: Prepare Monster Dev Template
    template: src=monster_template_dev.yml.j2 dest=/tmp/monster_template_dev.yml

  - name: Create monster dev template in openshift namespace
    shell: "oc create -f /tmp/monster_template_dev.yml -n openshift"
  when: "'monster-dev' not in templates.stdout_lines"

- block:
# Do one sample deployment to ensure docker images and maven dependencies
# are downloaded:
  - name: Doing sample deployment of monster-dev app
    shell: "oc new-app --template monster-dev -n ticketmonster-dev --labels=MonsterDevInitialDeploymentTest=true"

  - name: Wait for monster dev to become online
    shell: curl "http://monster-ticketmonster-dev.{{ ocp_apps_dns_domain }}/"
    register: tstcurl
    changed_when: false
    until: "'<title>Ticket Monster</title>' in tstcurl.stdout"
    retries: 480
    delay: 1

  - name: Removing sample deployment of monster-dev app
    shell: "oc delete all -l MonsterDevInitialDeploymentTest -n ticketmonster-dev"
  when: mode=="reset" or 'monster-dev' not in templates.stdout_lines

- block:
  - name: Prepare Monster Prod Template
    template: src=monster_template_prod.yml.j2 dest=/tmp/monster_template_prod.yml

  - name: Create monster prd template in openshift namespace
    shell: "oc create -f /tmp/monster_template_prod.yml -n openshift"

  - name: Grant Access to Images from ticketmonster-dev
    shell: "oc policy add-role-to-group system:image-puller system:serviceaccounts:ticketmonster-prod -n ticketmonster-dev"
  when: "'monster-prod' not in templates.stdout_lines"


# Create git  hook for ose3-ticket-monster inside git pod:
- block:
  - name: get git pod id
    shell: oc get pods -n devops-tools | grep git | awk '{ print $1 }'
    register: gitPod
    changed_when: false

  - file: path=/tmp/hooks state=directory

  - template: src=post-receive.j2 dest=/tmp/hooks/post-receive mode=a+x

  - name: Create git hook for monster
    shell: oc rsync /tmp/hooks/ {{ gitPod.stdout }}:/var/lib/git/ose3-ticket-monster.git/hooks  -n devops-tools --strategy=tar
  when: mode=="create" or mode=="reset"

# Create BuildPipeline in devops-tools to promote monster from ticketmonster-dev to ticketmonster-prod
- name: Grant devops-Jenkins access to ticketmonster-dev
  shell: oc policy add-role-to-user edit system:serviceaccount:devops-tools:jenkins -n ticketmonster-dev
- name: Grant devops-Jenkins access to ticketmonster-prod
  shell: oc policy add-role-to-user edit system:serviceaccount:devops-tools:jenkins -n ticketmonster-prod
- name: Prepare pipeline yaml
  template: src=monster_pipeline_devops.yml.j2 dest=/tmp/monster_pipeline_devops.yml
- name: Delete monster pipeline in devops project
  shell: "oc delete buildconfig ticketmonster-pipeline -n devops-tools"
  ignore_errors: true
- name: Create monster pipeline in devops project
  shell: "oc create -f /tmp/monster_pipeline_devops.yml -n devops-tools"
