# - name: create temp dir locally
#   local_action: command mktemp -d
#   register: mktemp
# - name: download CloudForms rake scripts
#   local_action: shell cd {{ mktemp.stdout }} && git clone https://github.com/rhtconsulting/cfme-rhconsulting-scripts.git
# - name: upload scripts zip file to CF
#   copy: src={{ mktemp.stdout }}/cfme-rhconsulting-scripts dest=/tmp/ mode=0644
# - name: remove temp dir locally
#   local_action: file name={{ mktemp.stdout }} state=absent
# - name: expand and install scripts
#   shell: cd /tmp/cfme-rhconsulting-scripts && make clean-install


#git is now available on the appliance
- name: clone git repo to appliance
  git: repo={{ cfme_rhconsulting_scripts_repo }}
       dest=/tmp/cfme-rhconsulting-scripts
  register: repo
- name: check current HEAD
  shell: cd /tmp/cfme-rhconsulting-scripts && git rev-parse HEAD
  register: head
  changed_when: false
- name: revert hailstorm branch to known good version
  shell: cd /tmp/cfme-rhconsulting-scripts && git reset --hard {{ current_lifecycle_env.cfme_rhconsulting_scripts_hash }}
  when: head.stdout != current_lifecycle_env.cfme_rhconsulting_scripts_hash
- name: make install
  shell: cd /tmp/cfme-rhconsulting-scripts && make clean-install && make clean
  when: repo|changed or head.stdout != current_lifecycle_env.cfme_rhconsulting_scripts_hash
