- block:
    - include: create_redhatmsa_project.yml
  when: mode == "create"

- block:
    - name: login to OpenShift
      shell: oc login --insecure-skip-tls-verify=true -u developer -p {{ root_password }} https://openshift.{{ hailstorm_dns_domain }}/ 
    - name: remove redhat-msa project
      shell: oc delete project {{ redhat_msa_project }}
    - name: remove workdirs
      file: state=absent path="{{ workdir }}/{{ item.name }}"
      with_items: "{{ msa_projects }}"
  become: true
  become_user: developer
  become_method: su
  when: mode == "destroy"
