- name: get all compute resources
  shell: hammer compute-resource list --organization "{{ organization }}" | awk '{ print $3}'
  register: compute_resources
  changed_when: false

- name: create RHEV compute resource
  command: hammer compute-resource create --organizations "{{ organization }}" --name rhev.{{ hailstorm_dns_domain }} --provider Ovirt --url https://rhev.{{ hailstorm_dns_domain }}{% if current_lifecycle_env.rhv_version == 4 %}/ovirt-engine{% endif %}/api --user admin@internal --password {{ root_password }}
  when: "'rhev.{{ hailstorm_dns_domain }}' not in compute_resources.stdout"
