- name: run purge-cluster playbook
  shell: cd /usr/share/ceph-ansible/infrastructure-playbooks && ansible-playbook purge-cluster.yml --extra-vars="ireallymeanit=yes" creates=/etc/ansible/hosts
  async: 7200
  poll: 0
  tags: ['playbook']
  register: playbook

- name: check on purge-cluster playbook completed
  async_status: jid={{ playbook.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 480
  delay: 15

- name: remove /etc/ansible/hosts (so installer will be run next time)
  file: path="/etc/ansible/hosts" state=absent
